name: Auto Push to GitHub

on:
  workflow_dispatch:
  push:
    branches: [main]
  delete:
    branches: [main]

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "[auto] Sync workspace changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
