name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest sphinx

      - name: Run tests
        run: |
          pytest

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html

      - name: Bump version and push tag
        run: |
          python bump_version_and_release.py

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Read release notes
        id: notes
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat RELEASE_NOTES.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Read release notes
        id: notes
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat RELEASE_NOTES.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.RELEASE_BODY }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "🚀 New release ${{ github.ref_name }} published! <${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 New release ${{ github.ref_name }} published! <${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}>"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
